#!/bin/bash

# [Experimental] Setup script for zsh aliases configuration with profile selection.
# Default behavior: Installs 'general' aliases only.
# Use '--profiles=ALL' to install everything, or specific names like '--profiles=git,brew'.
# Author: Artyom Ulanchik

set -e # Exit immediately if a command exits with a non-zero status

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZSHRC_PATH="$HOME/.zshrc"
ALIAS_SOURCE="$SCRIPT_DIR/.zsh_aliases"
ALIAS_DEST="$HOME/.zsh_aliases"
RC_EDIT_FILE="$SCRIPT_DIR/.zshrc_edit"

# Function to map profile keyword to section header string.
# This replaces the associative array to ensure compatibility with macOS default Bash (3.2).
get_profile_header() {
    local profile="$1"
    case "$profile" in
        "general")
            echo "General aliases"
            ;;
        "brew")
            echo "Homebrew aliases"
            ;;
        "git")
            echo "Git aliases"
            ;;
        "pnpm")
            echo "PNPM"
            ;;
        "vscprofiles")
            echo "VSCode Profile aliases"
            ;;
        *)
            # Unknown profile
            echo ""
            ;;
    esac
}

# Helper to list available profiles for error messages
get_available_profiles() {
    echo "general, brew, git, pnpm, vscprofiles"
}

usage() {
    echo "Usage: $0 [--profiles=<profile_list>]"
    echo ""
    echo "Arguments:"
    echo "  --profiles=<list>, -p=<list>   Optional. Comma-separated list of profiles."
    echo "                                 Special value: 'ALL' (installs every section)."
    echo ""
    echo "Behavior:"
    echo "  (no args)                     Installs ONLY 'general' aliases (safe defaults)."
    echo "  --profiles=ALL                 Installs ALL available profiles."
    echo "  --profiles=git                 Installs only Git aliases."
    echo "  --profiles=git,brew            Installs Git and Homebrew aliases."
    echo ""
    echo "Available profiles: $(get_available_profiles)"
    exit 0
}

log_info() {
    echo "[INFO] $1"
}

log_error() {
    echo "[ERROR] $1" >&2
}

log_warn() {
    echo "[WARN] $1" >&2
}

# Function to extract specific sections from .zsh_aliases
extract_profiles() {
    local source_file="$1"
    local dest_file="$2"
    local mode="$3" # 'specific' or 'all'
    shift 3
    local selected_profiles=("$@")
    
    # Create/clear destination file
    > "$dest_file"
    
    # Add header to generated file
    echo "# Generated by setup.sh on $(date)" >> "$dest_file"
    if [ "$mode" == "all" ]; then
        echo "# Mode: ALL profiles included" >> "$dest_file"
    elif [ ${#selected_profiles[@]} -eq 0 ]; then
        echo "# Mode: Default (General only)" >> "$dest_file"
    else
        echo "# Mode: Specific profiles: ${selected_profiles[*]}" >> "$dest_file"
    fi
    echo "" >> "$dest_file"
    
    local current_section=""
    local include_section=false
    local found_any=false
    local any_section_found=false

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Check if line is a section header (starts with # and contains text)
        if [[ "$line" =~ ^#[[:space:]]*(.*) ]]; then
            local header_text="${BASH_REMATCH[1]}"
            current_section="$header_text"
            include_section=false
            
            # Skip empty comments or generator headers we just added
            if [[ -z "$header_text" || "$header_text" == "Generated"* ]]; then
                echo "$line" >> "$dest_file"
                continue
            fi

            any_section_found=true

            # Determine if this section should be included
            if [ "$mode" == "all" ]; then
                include_section=true
                found_any=true
            else
                # Check against selected profiles
                for profile in "${selected_profiles[@]}"; do
                    local expected_header
                    expected_header=$(get_profile_header "$profile")
                    
                    if [[ -n "$expected_header" && "$current_section" == *"$expected_header"* ]]; then
                        include_section=true
                        found_any=true
                        break
                    fi
                done
            fi
            
            # Write the header comment regardless of inclusion (keeps file readable)
            echo "$line" >> "$dest_file"
            
        else
            # If we're in a selected section, include the content line
            if [ "$include_section" = true ]; then
                echo "$line" >> "$dest_file"
            fi
        fi
    done < "$source_file"
    
    if [ "$any_section_found" = false ]; then
        log_warn "No section headers found in source file. Copying raw content?"
    fi

    if [ "$mode" != "all" ] && [ ${#selected_profiles[@]} -gt 0 ] && [ "$found_any" = false ]; then
        log_error "No matching sections found for profiles: ${selected_profiles[*]}"
        log_error "Available profiles: $(get_available_profiles)"
        return 1
    fi
    
    return 0
}

PROFILES_INPUT=""
SELECTED_PROFILES=()
MODE="default" # Options: default, specific, all

while [[ $# -gt 0 ]]; do
    case $1 in
        --profiles=*|-p=*)
            # Extract value after the '=' sign
            PROFILES_INPUT="${1#*=}"
            
            if [ "$PROFILES_INPUT" == "ALL" ]; then
                MODE="all"
            else
                MODE="specific"
                # Split comma-separated values into array
                IFS=',' read -ra SELECTED_PROFILES <<< "$PROFILES_INPUT"
                # Trim whitespace from each profile
                SELECTED_PROFILES=("${SELECTED_PROFILES[@]// /}")
            fi
            shift
            ;;
        --help|-h)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            log_error "Use '=' sign for arguments, e.g., --profiles=git,brew"
            usage
            ;;
    esac
done

log_info "Starting zsh aliases setup..."

# Determine final profile list for logging/logic
if [ "$MODE" == "default" ]; then
    # If no args provided, force 'general'
    SELECTED_PROFILES=("general")
    log_info "No profiles specified. Using DEFAULT mode: 'general' only."
elif [ "$MODE" == "all" ]; then
    log_info "Mode: ALL profiles will be installed."
else
    log_info "Mode: Specific profiles requested: ${SELECTED_PROFILES[*]}"
fi

# Check if .zsh_aliases exists
if [ ! -f "$ALIAS_SOURCE" ]; then
    log_error "File '.zsh_aliases' not found in current directory ($SCRIPT_DIR)."
    log_error "Please run this script from the repository root."
    exit 1
fi

# Check if .zshrc_edit exists
if [ ! -f "$RC_EDIT_FILE" ]; then
    log_error "File '.zshrc_edit' not found. This file is required to update .zshrc."
    exit 1
fi

TEMP_ALIAS_FILE=$(mktemp)
trap "rm -f $TEMP_ALIAS_FILE" EXIT # Ensure cleanup on exit

if [ "$MODE" == "all" ]; then
    if ! extract_profiles "$ALIAS_SOURCE" "$TEMP_ALIAS_FILE" "all"; then
        exit 1
    fi
else
    if ! extract_profiles "$ALIAS_SOURCE" "$TEMP_ALIAS_FILE" "specific" "${SELECTED_PROFILES[@]}"; then
        exit 1
    fi
fi

# Check if generated file has content (beyond comments)
if [ ! -s "$TEMP_ALIAS_FILE" ]; then
    log_error "Generated alias file is empty."
    exit 1
fi

# Count non-comment lines to ensure we actually got aliases
alias_count=$(grep -v '^#' "$TEMP_ALIAS_FILE" | grep -v '^$' | wc -l)
if [ "$alias_count" -eq 0 ]; then
    log_error "Generated file contains no active aliases. Check section headers."
    exit 1
fi

# --- Backup Logic (in case of anything goes wrong) ---

# Backup existing .zsh_aliases if it exists
if [ -f "$ALIAS_DEST" ]; then
    BACKUP_NAME="${ALIAS_DEST}.backup.$(date +%Y%m%d_%H%M%S)"
    log_info "Backing up existing .zsh_aliases to $(basename "$BACKUP_NAME")"
    cp "$ALIAS_DEST" "$BACKUP_NAME"
fi

# Backup .zshrc before modifying
if [ -f "$ZSHRC_PATH" ]; then
    RC_BACKUP="${ZSHRC_PATH}.backup.$(date +%Y%m%d_%H%M%S)"
    log_info "Backing up existing .zshrc to $(basename "$RC_BACKUP")"
    cp "$ZSHRC_PATH" "$RC_BACKUP"
else
    log_info "Warning: $ZSHRC_PATH not found. Creating it."
    touch "$ZSHRC_PATH"
fi

# --- Installation ---

# Copy generated alias file to home directory
mv "$TEMP_ALIAS_FILE" "$ALIAS_DEST"
log_info "Generated .zsh_aliases installed to $HOME"

# Show summary
if [ "$MODE" == "all" ]; then
    log_info "Included: ALL profiles"
else
    log_info "Included profiles: ${SELECTED_PROFILES[*]}"
fi

# Check if sourcing is already in .zshrc
SOURCE_LINE='source "$HOME/.zsh_aliases"'
if grep -qF "$SOURCE_LINE" "$ZSHRC_PATH"; then
    log_info "Sourcing logic already present in .zshrc"
else
    log_info "Appending sourcing logic to .zshrc"
    echo "" >> "$ZSHRC_PATH"
    cat "$RC_EDIT_FILE" >> "$ZSHRC_PATH"
fi

# --- Final steps ---

# Verify .zshrc syntax if zsh is available
if command -v zsh &> /dev/null; then
    if ! zsh -n "$ZSHRC_PATH" 2>/dev/null; then
        log_error "Warning: .zshrc has syntax errors. Please check manually."
        log_error "Restore backup with: cp $(ls -t ${ZSHRC_PATH}.backup.* | head -n 1) $ZSHRC_PATH"
    else
        log_info ".zshrc syntax check passed."
    fi
fi

# Attempt to source only if we are in an interactive shell session
if [[ $- == *i* ]]; then
    log_info "Sourcing .zshrc to apply changes immediately..."
    source "$ZSHRC_PATH"
    log_info "Setup complete! Zsh aliases are now available in your current session."
else
    log_info "Setup complete!"
    log_info "Changes applied. Restart terminal or run 'source $ZSHRC_PATH' to apply."
fi
